//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_Test_1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Documents = new HashSet<Document>();
        }

        [StringLength(13, MinimumLength = 13, ErrorMessage = "Please enter a valid ID number (13 Digits)")]
        [Required(ErrorMessage = "ID number is required")]
        public string Client_ID { get; set; }

        [Display(Name = "Client Name")]
        public string Client_Name { get; set; }

        [Display(Name = "Client Surname")]
        public string Client_Surname { get; set; }

        [Display(Name = "Client Age")]
        public string Client_Age { get; set; }

        [Display(Name = "Client DOB")]
        public string Client_DOB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
    }
}
