//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_Test_1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public class EmpModel
    {
        [Required(ErrorMessage ="Please Select a File")]
        [DataType(DataType.Upload)]
        [Display(Name = "Select File")]
        public HttpPostedFileBase files { get; set; }
    }
    public partial class Document
    {
        
        public int Doc_ID { get; set; }
        public string Doc_Name { get; set; }
        public byte[] Doc_Content { get; set; }
        public string Client_ID { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
